package com.project;

import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfPageEventHelper;

import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.*;

public class AssignmentReportServlet extends HttpServlet {

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        HttpSession session = request.getSession(false);
        if (session == null || session.getAttribute("user") == null) {
            response.sendRedirect("error_session.jsp");
            return;
        }

        String currentUser = (String) session.getAttribute("user");
        String from = request.getParameter("fromDate");
        String to = request.getParameter("toDate");

        // Timestamped filename
        String timestamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
        String fileName = "ASSIGNMENTS_" + timestamp + ".pdf";

        response.setContentType("application/pdf");
        response.setHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");

        try {
            // Landscape page
            Document document = new Document(PageSize.LETTER.rotate());
            PdfWriter writer = PdfWriter.getInstance(document, response.getOutputStream());

            // Headers/footers from DD + pagination
            ReportPageEvent event = new ReportPageEvent(currentUser, getServletContext());
            writer.setPageEvent(event);

            document.open();

            Font titleFont = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
            Font normalFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);

            Paragraph titlePara = new Paragraph("ASSIGNMENT REPORT", titleFont);
            titlePara.setAlignment(Element.ALIGN_CENTER);
            titlePara.setSpacingAfter(15f);
            document.add(titlePara);

            document.add(new Paragraph("Generated by: " + currentUser, normalFont));
            document.add(new Paragraph("Generated on: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()), normalFont));

            if (from != null && !from.isEmpty() && to != null && !to.isEmpty()) {
                document.add(new Paragraph("Date range: " + from + " to " + to, normalFont));
            }
            document.add(new Paragraph(" "));

            // Build SQL with optional time‑bound filter on due_date
            String sql = "SELECT id, title, course_id, due_date FROM assignments";
            boolean hasDateFilter = (from != null && !from.isEmpty() && to != null && !to.isEmpty());
            if (hasDateFilter) {
                sql += " WHERE due_date BETWEEN ? AND ?";
            }
            sql += " ORDER BY due_date";

            // PostgreSQL connection from web.xml
            ServletContext ctx = getServletContext();
            String driver = ctx.getInitParameter("postgresDriver");
            String url = ctx.getInitParameter("postgresURL");
            String dbUser = ctx.getInitParameter("postgresUser");
            String dbPass = ctx.getInitParameter("postgresPass");

            Class.forName(driver);
            Connection conn = DriverManager.getConnection(url, dbUser, dbPass);
            PreparedStatement ps = conn.prepareStatement(sql);

            if (hasDateFilter) {
                ps.setDate(1, java.sql.Date.valueOf(from));
                ps.setDate(2, java.sql.Date.valueOf(to));
            }

            ResultSet rs = ps.executeQuery();

            // Collect rows for pagination
            List<String[]> rows = new ArrayList<>();
            while (rs.next()) {
                rows.add(new String[]{
                    String.valueOf(rs.getInt("id")),
                    rs.getString("title"),
                    String.valueOf(rs.getInt("course_id")),
                    rs.getDate("due_date").toString()
                });
            }
            rs.close();
            conn.close();

            // Pagination: 20 rows per page
            int rowsPerPage = 20;
            int totalRows = rows.size();
            int totalPages = (int) Math.ceil((double) totalRows / rowsPerPage);
            int pageNum = 0;

            for (int start = 0; start < totalRows; start += rowsPerPage) {
                pageNum++;
                int end = Math.min(start + rowsPerPage, totalRows);

                PdfPTable table = new PdfPTable(4);
                table.setWidthPercentage(100);
                table.addCell(createHeaderCell("ID"));
                table.addCell(createHeaderCell("Title"));
                table.addCell(createHeaderCell("Course ID"));
                table.addCell(createHeaderCell("Due Date"));

                for (int i = start; i < end; i++) {
                    String[] row = rows.get(i);
                    table.addCell(createDataCell(row[0]));
                    table.addCell(createDataCell(row[1]));
                    table.addCell(createDataCell(row[2]));
                    table.addCell(createDataCell(row[3]));
                }

                document.add(table);

                if (pageNum < totalPages) {
                    document.newPage();
                }
            }

            document.close();

        } catch (Exception e) {
            throw new ServletException(e);
        }
    }

    private PdfPCell createHeaderCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD)));
        cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(5);
        return cell;
    }

    private PdfPCell createDataCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, new Font(Font.FontFamily.HELVETICA, 10)));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(5);
        return cell;
    }

    // Inner class for DD headers/footers and page numbers
    class ReportPageEvent extends PdfPageEventHelper {
        private String owner;
        private ServletContext context;
        private PdfTemplate total;

        public ReportPageEvent(String owner, ServletContext context) {
            this.owner = owner;
            this.context = context;
        }

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            total = writer.getDirectContent().createTemplate(30, 16);
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();

            // Header from web.xml
            String headerText = context.getInitParameter("headerTitle");
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                new Phrase(headerText, new Font(Font.FontFamily.HELVETICA, 10)),
                (document.left() + document.right()) / 2,
                document.top() + 15, 0);

            // Footer left: Owner
            ColumnText.showTextAligned(cb, Element.ALIGN_LEFT,
                new Phrase("Owner: " + owner, new Font(Font.FontFamily.HELVETICA, 10, Font.ITALIC)),
                document.leftMargin(), document.bottomMargin() - 15, 0);

            // Footer right: Page X of Y
            String pageStr = "Page " + writer.getPageNumber() + " of ";
            float textBase = document.bottomMargin() - 15;
            ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT,
                new Phrase(pageStr, new Font(Font.FontFamily.HELVETICA, 10)),
                document.right() - 30, textBase, 0);
            cb.addTemplate(total, document.right() - 30 + 4, textBase);

            // Footer centre: web.xml footer
            String footerText = context.getInitParameter("footerInfo");
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                new Phrase(footerText, new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC)),
                (document.left() + document.right()) / 2,
                document.bottomMargin() - 30, 0);
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            ColumnText.showTextAligned(total, Element.ALIGN_LEFT,
                new Phrase(String.valueOf(writer.getPageNumber()), new Font(Font.FontFamily.HELVETICA, 10)),
                0, 0, 0);
        }
    }
}