// ReportServlet.java (enhanced)
package com.project;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.*;

public class ReportServlet extends HttpServlet {

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException {

    HttpSession session = request.getSession(false);
    if (session == null || session.getAttribute("user") == null) {
        response.sendRedirect("error_session.jsp");
        return;
    }

    String currentUser = (String) session.getAttribute("user");
    String currentRole = (String) session.getAttribute("role");

    // Parameters from UI
    String type = request.getParameter("type");  // "all" or "own"
    String from = request.getParameter("fromDate"); // yyyy-MM-dd
    String to = request.getParameter("toDate");

    // Determine report title and SQL where clause
    String reportTitle;
    String sql;
    boolean isAdmin = "admin".equals(currentRole);

    if (isAdmin && "own".equals(type)) {
        reportTitle = "MY RECORD";
        sql = "SELECT username, role FROM USERS WHERE username = ?";
    } else if (isAdmin && "all".equals(type)) {
        reportTitle = "ALL USERS";
        sql = "SELECT username, role FROM USERS";
    } else {
        // guest always prints own record
        reportTitle = "GUEST RECORD";
        sql = "SELECT username, role FROM USERS WHERE username = ?";
    }

    // Build dynamic SQL for time-bound filtering (applies to ALL records only)
    if (isAdmin && "all".equals(type) && from != null && !from.isEmpty()
            && to != null && !to.isEmpty()) {
        sql += " WHERE created_date BETWEEN ? AND ?";
    }

    // Landscape page size
    Document document = new Document(PageSize.LETTER.rotate());

    // Timestamp for filename
    String timestamp = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
    String fileName = "COURSELIST_" + timestamp + ".pdf";

    // Force download (client side)
    response.setContentType("application/pdf");
    response.setHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\"");

    try {
        PdfWriter writer = PdfWriter.getInstance(document, response.getOutputStream());

        // Page event for header/footer from DD and page numbers
        ReportPageEvent event = new ReportPageEvent(currentUser, getServletContext());
        writer.setPageEvent(event);

        document.open();

        Font boldFont = new Font(Font.FontFamily.HELVETICA, 16, Font.BOLD);
        Font normalFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL);

        // Title
        Paragraph titlePara = new Paragraph(reportTitle, boldFont);
        titlePara.setAlignment(Element.ALIGN_CENTER);
        titlePara.setSpacingAfter(15f);
        document.add(titlePara);

        // Username & generation time
        document.add(new Paragraph("Generated by: " + currentUser, normalFont));
        document.add(new Paragraph("Generated on: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()), normalFont));
        if (from != null && to != null && !from.isEmpty() && !to.isEmpty()) {
            document.add(new Paragraph("Date Range: " + from + " to " + to, normalFont));
        }
        document.add(new Paragraph(" "));

        // Database connection (Derby for this report)
        String driver = getServletConfig().getInitParameter("dbDriver");
        String url = getServletConfig().getInitParameter("dbURL");
        String dbUser = getServletConfig().getInitParameter("dbUser");
        String dbPass = getServletConfig().getInitParameter("dbPass");

        Class.forName(driver);
        Connection conn = DriverManager.getConnection(url, dbUser, dbPass);

        PreparedStatement ps = conn.prepareStatement(sql);
        int paramIndex = 1;
        if (isAdmin && "own".equals(type) || !isAdmin) {
            ps.setString(paramIndex++, currentUser);
        }
        if (isAdmin && "all".equals(type) && from != null && !from.isEmpty()
                && to != null && !to.isEmpty()) {
            // **** FIX: catch date parsing errors ****
            try {
                ps.setDate(paramIndex++, java.sql.Date.valueOf(from));
                ps.setDate(paramIndex++, java.sql.Date.valueOf(to));
            } catch (IllegalArgumentException e) {
                conn.close();
                response.sendRedirect("error_date.jsp");
                return;
            }
        }

        ResultSet rs = ps.executeQuery();

        // Build a list to support pagination
        java.util.List<String[]> rows = new java.util.ArrayList<>();
        while (rs.next()) {
            String username = rs.getString("username");
            String role = rs.getString("role");
            rows.add(new String[]{username, role});
        }
        rs.close();
        conn.close();

        // Pagination: max 40 rows per page
        int rowsPerPage = 51;   
        int totalRows = rows.size();
        int totalPages = (int) Math.ceil((double) totalRows / rowsPerPage);
        int pageNum = 0;

        for (int start = 0; start < totalRows; start += rowsPerPage) {
            pageNum++;
            int end = Math.min(start + rowsPerPage, totalRows);

            // Table header
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);
            table.addCell(createHeaderCell("Username"));
            table.addCell(createHeaderCell("Role"));

            // Data rows
            for (int i = start; i < end; i++) {
                String[] row = rows.get(i);
                String user = row[0];
                String role = row[1];

                // Asterisk (*) beside current admin’s name in all-records report
                if (isAdmin && "all".equals(type) && user.equals(currentUser)) {
                    user = user + " *";
                }

                table.addCell(createDataCell(user));
                table.addCell(createDataCell(role));
            }

            document.add(table);

            // Page break unless it's the last page
            if (pageNum < totalPages) {
                document.newPage();
            }
        }

        document.close();

    } catch (Exception e) {
        e.printStackTrace();   // log the real error
        // If the response is not committed, redirect to error page
        if (!response.isCommitted()) {
            response.sendRedirect("error_db.jsp");
        }
    }
}

    private PdfPCell createHeaderCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD)));
        cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(8f);
        return cell;
    }

    private PdfPCell createDataCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, new Font(Font.FontFamily.HELVETICA, 10)));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(8f);
        return cell;
    }

    // Inner class for header/footer from DD and page X of Y
    class ReportPageEvent extends PdfPageEventHelper {
        private String owner;
        private ServletContext context;
        private PdfTemplate total;

        public ReportPageEvent(String owner, ServletContext context) {
            this.owner = owner;
            this.context = context;
        }

        @Override
        public void onOpenDocument(PdfWriter writer, Document document) {
            total = writer.getDirectContent().createTemplate(30, 16);
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContent();

            // Header from web.xml (top of page)
            String headerText = context.getInitParameter("headerTitle");
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                new Phrase(headerText, new Font(Font.FontFamily.HELVETICA, 10)),
                (document.left() + document.right()) / 2,
                document.top() + 15, 0);

            // Footer left: "Owner: ..."
            ColumnText.showTextAligned(cb, Element.ALIGN_LEFT,
                new Phrase("Owner: " + owner, new Font(Font.FontFamily.HELVETICA, 10, Font.ITALIC)),
                document.leftMargin(), document.bottomMargin() - 15, 0);

            // Footer right: Page X of Y
            String pageStr = "Page " + writer.getPageNumber() + " of ";
            float textBase = document.bottomMargin() - 15;
            ColumnText.showTextAligned(cb, Element.ALIGN_RIGHT,
                new Phrase(pageStr, new Font(Font.FontFamily.HELVETICA, 10)),
                document.right() - 30, textBase, 0);
            cb.addTemplate(total, document.right() - 30 + 4, textBase);

            // Footer centre: from web.xml
            String footerText = context.getInitParameter("footerInfo");
            ColumnText.showTextAligned(cb, Element.ALIGN_CENTER,
                new Phrase(footerText, new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC)),
                (document.left() + document.right()) / 2,
                document.bottomMargin() - 30, 0);
        }

        @Override
        public void onCloseDocument(PdfWriter writer, Document document) {
            ColumnText.showTextAligned(total, Element.ALIGN_LEFT,
                new Phrase(String.valueOf(writer.getPageNumber()), new Font(Font.FontFamily.HELVETICA, 10)),
                0, 0, 0);
        }
    }
}